### PR TITLE
Fixes mostly-adequate-guide/#269, adds Babel to part2_exercises/packa…

### PR DESCRIPTION
**Pull request by thurt**
…ge.json to allow Mocha tests to run with ES6 syntax, modifies `part2_exercises/package.json` scripts, modifies `part2_exercises/readme.md` to reflect script changes

I ran into a couple problems after setting up babel.

SyntaxError in `part1_exercises/support.js`: Assigning to arguments in strict mode (51:6)
- resolved with `var _arguments = Array.prototype.slice.call(arguments)`

ReferenceErrors for global variables in `part2_exercises/support.js`
- resolved by adding `global.` prefix to global variables

side note: I find it odd that there are separate package.json for part1 and part2. It seems like these should be merged so that there is only one package.json for both.

### CODE REVIEW

**Comment by thurt** [comment]
I'm disappointed in Mocha. It's a pain to have to use Babel transpile (ES6->ES5) in order to run tests... meh

**Comment by christiantakle** [comment]
@thurt Thank you. I will merge it later.

I agree with you this seems we should be able to simplify the runnable code quite a bit.

Do you have some proposals other than Mocha?

**Comment by thurt** [comment]
> Do you have some proposals other than Mocha?

ping @DrBoolean 
Well...I was hoping you might have another idea? Maybe there is no good alternative yet for testing ES6 code. But it does work and tests run fine for part2 with the way I have it setup in this PR. I don't think there should be any problems from the babel transpiler.

:bulb:'s for `code` folder: 

- [ ] merge package.json files into one
- [ ] instead of part1 and part2 folders, change folder structure so answers/exercises are in folders by chapter

**Comment by DrBoolean** [comment]
Sorry for the late reply. I haven't needed babel in node since 6 dropped. I think we can just run mocha like normal, no?

Love the ideas, btw. I backed myself into this structure and never took time to clean it

**Comment by christiantakle** [comment]
@DrBoolean I think so - I merged it in order to rewrite most of the code. Its nicer to work from solid foundation than merging at a later point.

I'm working on it right now.

**Comment by thurt** [comment]
ah great point! I was using node v5.4.0.
@christiantakle 
1. confirmed works with node v6.2.0 
2. remove "--require babel-core/register" from scripts
3. npm un babel-core babel-cli babel-preset-es2015

I get warning when running scripts: 
`(node:2639) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.`

Not sure what it means

**Pull request merged**
